"""Add profile pic

Revision ID: 56470e859836
Revises: dcb04560b057
Create Date: 2020-12-21 19:14:44.543666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56470e859836'
down_revision = 'dcb04560b057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profilepic', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profilepic')
    # ### end Alembic commands ###
